name: Format check

on:
  pull_request:
    branches: [development, main, beta] # or whatever branch you protect
  workflow_dispatch:
    branches: [development, main, beta]
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Satisfy dependencies
        run: yarn install --frozen-lockfile
      - name: Check console usages
        run: yarn console:check
      - name: Check lifecycle regions
        run: yarn region:check
      - name: Check method count
        run: yarn method:check
      - name: Check type blowout
        run: yarn type:check
