name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    branches: [main]
    
jobs:
  deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Write env file
        run: |
          echo "DW_SERVER_URL=\"https://test.arcapi.nl\"" > .env
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: yarn build
      - name: Upload build to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "84.25.42.134"
          username: "deploy"
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACC3nIFpo/b+t/9cEeu/TdOm5WZlHdQxXpL4Ha27iR9QywAAAKDq7a8T6u2v
            EwAAAAtzc2gtZWQyNTUxOQAAACC3nIFpo/b+t/9cEeu/TdOm5WZlHdQxXpL4Ha27iR9Qyw
            AAAEDQYWbAzjpd9qyjZik09pYevcdpQdU7UfLC6Ca5G+4TMbecgWmj9v63/1wR679N06bl
            ZmUd1DFekvgdrbuJH1DLAAAAGGRlcGxveUBwcmV2aWV3LmFyY3dlYi5ubAECAwQF
            -----END OPENSSH PRIVATE KEY-----
            
          port: 28
          source: "dist/*"
          target: "/home/izaak/ArcOS/v7previews/${{ github.head_ref }}/"
